model_configs_path: 'model_configs_example.csv'
llm_api: 'sncloud'
# output_files_dir: '../data/prompt_caching_tests/no_prompt_caching'
# consolidated_results_dir: '../data/prompt_caching_tests/no_prompt_caching/consolidated_results'
output_files_dir: '../data/ignore_eos/with_ignore_eos'
consolidated_results_dir: '../data/ignore_eos/with_ignore_eos/consolidated_results'
timeout: 3600
time_delay: 30
# Row-level concurrency
concurrency_enabled: False
max_workers: 4 # Only used if concurrency_enabled is True
# Prompt behavior
use_multiple_prompts : False # Only available for synthetic performance evaluation