model_configs_path: '../benchmarking/benchmarking_bundles/model_configs_example.csv'
llm_api: 'sncloud'
output_files_dir: '../benchmarking/data/bundle_tests/paytm_bundle/switching_time/12tb/switch/output_files'
consolidated_results_dir: '../benchmarking/data/bundle_tests/paytm_bundle/switching_time/12tb/switch/consolidated_results'
timeout: 3600
time_delay: 0
# Row-level concurrency
concurrency_enabled: False
max_workers: 4 # Only used if concurrency_enabled is True
# Prompt behavior
use_multiple_prompts : False # Only available for synthetic performance evaluation