api: "sncloud"  #  set either sambastudio or sncloud

embedding_model: 
    "type": "sambastudio" # set either sambastudio or cpu
    "batch_size": 1 #set depending of your endpoint configuration (1 if CoE embedding expert)
    "coe": False #set true if using Sambastudio embeddings in a CoE endpoint 
    "select_expert": "e5-mistral-7b-instruct" #set if using SambaStudio CoE embedding expert

router: 
    "type": "sncloud" # set either sambastudio or sncloud
    "temperature": 0.0
    "do_sample": False
    "max_tokens_to_generate": 1200
    "coe": True #set as true if using Sambastudio CoE endpoint
    "select_expert": "llama3-8b" #set if using sncloud, or SambaStudio CoE llm expert
    "document_folder": "router/data" # path of documents
    "keyword_path": "router/keywords/keywords_3.pkl" # path to save keywords
    "use_clusters": False # set True if extract keywords from only one document in each cluster
    "use_bert": True # set True if use embedding and cosine similarity to extract keywords
    "use_llm": False # set True if use llm to extract keywords

llm: 
    "temperature": 0.0
    "do_sample": False
    "max_tokens_to_generate": 1200
    "coe": True #set as true if using Sambastudio CoE endpoint
    "select_expert": "llama3-8b" #set if using sncloud, or SambaStudio CoE llm expert
    #sncloud CoE expert name -> "llama3-8b"

retrieval:
    "k_retrieved_documents": 15 #set if rerank enabled 
    "score_threshold": 0.2
    "rerank": False # set if you want to rerank retriever results 
    "reranker": 'BAAI/bge-reranker-large' # set if you rerank enabled
    "final_k_retrieved_documents": 5

prompts: 
    "router_prompt": "router/prompts/rag_routing_prompt.yaml"
    "qa_prompt": "enterprise_knowledge_retriever/prompts/qa_prompt.yaml"
    "kw_etr_prompt": "router/prompts/keyword_extractor_prompt.yaml"

