llm: 
    "temperature": 0.0
    "top_p": null
    "top_k": null
    "max_tokens": 8912
    "model": "gpt-oss-120b"

lvlm:
    "model": "gemma-3-12b-it"
    "max_tokens": 8912 
    "temperature": 1
    "top_k": 50
    "top_p": 1

embedding_model:
    "model": "intfloat/e5-large-v2"

retrieval:
    "max_characters": 800
    "new_after_n_chars": 500
    "combine_text_under_n_chars": 300
    "k_retrieved_documents": 4

prod_mode: False
