personalized_activity_planning_task:
  description: >
    Research and find cool things to do at {destination}.
    Focus on activities and events that match the traveler's interests and age group.
    Utilize internet search tools and recommendation engines to gather the information.

    Traveler's information:

    - origin: {origin}

    - destination: {destination}

    - Approximate age of the adult travelers: {age}

    - List of interests that the traveller may have: {interests}

    - List of cuisine preferences that the traveller may have: {cuisine_preferences}

    - Are children accompanying the trip: {children}

    - how long is the trip: {trip_duration}

    - budget for entire trip in dollars: {budget}
  expected_output: >
    A list of recommended activities and events for each day of the trip.
    Each entry should include the activity name, location including a brief description, and why it's suitable for the traveler.
    The location should have the full address so that it can be easily found using a map.
    And potential reviews and ratings of the activities.

restaurant_scenic_location_scout_task:
  description: >
    Find highly-rated restaurants and dining experiences for the specific cuisine interests {cuisine_preferences} at {destination}.
    Pay particular attention to the cuisines. As an example, if vegan is on the list, then recommend restaurants which accomodate vegan diet.
    Recommend scenic locations that align with the traveler's preferences and activities.
    Use internet search tools, restaurant review sites, and travel guides.
    Make sure to find a variety of options to suit different tastes and budgets, and ratings for them.
    Extract the address of the restaurant so that the same can be displayed to the user.

    Traveler's information:

    - origin: {origin}

    - destination: {destination}

    - age of the traveler: {age}

    - List of cuisine preferences that the traveller may have: {cuisine_preferences}

    - how long is the trip: {trip_duration}

    - budget for entire trip in dollars: {budget}
  expected_output: >
    A list of recommended restaurants for each day of the trip.
    Each entry should include the name, location including a detailed address, type of cuisine or activity, and a brief description and ratings.

interest_scout_task:
  description: >
    Run specifically for the interests of the traveller provided {interests}. As an example if the traveller has interest in museums, plan activities related to museums at the destination.
    Check if children are accompanying in the trip. {children}
    If children are accompanying, find activities that might be more appealing to children.
    Use internet search tools, review sites, feedback from users, and travel guides.
    Extract the address of the activity so that the same can be displayed to the user.

    Traveler's information:

    - origin: {origin}

    - destination: {destination}

    - age of the traveler: {age}

    - List of interests that the traveller may have: {interests}

    - Are children accompanying the trip: {children}

    - how long is the trip: {trip_duration}

    - budget for entire trip in dollars: {budget}
  expected_output: >
    A list of recommended activities. There must be at least one activity for each day of the trip. Allocate appropriate time for the activity so that the traveller need not rush to the next activity.
    Each entry should include the name, location including a detailed address, type of cuisine or activity, and a brief description and ratings.


itinerary_compilation_task:
  description: >
    Compile all researched information into a comprehensive day-by-day itinerary for the trip to {destination}.
    Include information relevant to the traveler's interests. For example, if the traveller is not interested in museums, do not pack the itinerary with museums.
    Ensure the itinerary integrates hotel information and all planned activities and dining experiences.
    Make sure that you do not recommend the same restaurant for both lunch and dinner.
    Use text formatting and document creation tools to organize the information.
    Do a great job so that you can be proud of your work.
  expected_output: >
    A detailed itinerary document, the itinerary should include a day-by-day
    plan with activities, restaurants, and scenic locations. Include the address for each location so that a user can easily go to the address. A day can contain multiple activities. In such a case a recommended mode of transport should be provided to help move from one activity location to another.
