draft:
  model:
    model_name: "Llama-3.1-8B-Instruct"
    publisher: "meta-llama"
    description: "The Meta Llama 3.1 collection of multilingual large language models (LLMs) is a collection of pretrained and instruction tuned generative models in 8B, 70B and 405B sizes (text in/text out)."
    param_count: 8  # number in billions of parameters

  sambastudio:
    snapi_path: ""
    rdu_arch: "SN40L-8"

  # checkpoints:
  #   - model_name: "Llama-3.2-3B-Instruct"
  #     checkpoint_path: '/Users/francescar/Documents/ai-starter-kit/e2e_draft_model_training/data/models/models--meta-llama--Llama-3.2-3B-Instruct/snapshots/0cb88a4f764b7a12671c53f0838cd831a0843b95'
  #     publisher: "meta-llama"
  #     description: "The `Llama 3.2` collection of multilingual large language models (LLMs) is a collection of pretrained and instruction-tuned generative models in 1B and 3B sizes (text in/text out)."
  #     param_count: 3
  #     model_arch: "llama" 
  #     seq_length: 131072 
  #     vocab_size: 128256 
  #     app_id: "49683c7f-3e42-4217-96dd-6f975d17c393"