model_checkpoint:
  checkpoint_name: "" #set after listing the generated checkpoints after training
  model_name: "meta-llama-3.1-8b-instruct"
  model_description: "The Meta Llama 3.1 collection of multilingual large language models (LLMs) is a collection of pretrained and instruction tuned generative models in 8B, 70B and 405B sizes (text in/text out)."
  model_type: "finetuned"

dataset:
  dataset_name: "dummy_example"
  dataset_description: "xxx"

project:
  project_name: "e2e-draft-model-training-project"
  project_description: "This project will be used to test the E2E Draft Model Training pipeline implementation."

sambastudio:
  snapi_path: ""
  rdu_arch: "SN40L-8"