sambastudio:
  snapi_path: ""
  rdu_arch: "SN40L-16"

dataset:
  dataset_name: "smol_sql_dataset"
  dataset_description: "test_dataset for sql fine-tuning"
  dataset_path: "/Users/your-user/Documents/ai-starter-kit/utils/fine_tuning/sambastudio_fine_tuning_dataset"
  dataset_apps_availability: 
    - 'Mistral'
    - 'Llama 3'
    - 'Llama 3.1'
    - 'Llama 3.2'
    - 'Samba1 Llama3 Experts'
    - 'Samba1 Llama3.1 Experts'
    - 'Samba1 Llama3.2 Experts'
    - 'Samba1 Llama3.3 Experts'
    - 'Samba1 Mistral Experts'
    - 'Samba1 Gemma Experts'
    - 'Samba1 Qwen2 Experts'
    - 'Samba1 Qwen2.5 Experts'
    - 'Samba1 Mistral Experts'
  dataset_job_types:
    - "evaluation"
    - "train"
  dataset_source_type: "localMachine"
  dataset_language: "english"
  dataset_filetype: "hdf5"
  dataset_url: ""
  dataset_metadata:
    labels_file: ""
    train_filepath: ""
    validation_filepath: ""
    test_filepath: ""
  
project: 
  project_name: "example project"
  project_description: "this project will be used to test fine-tuning"

job:
  job_name: "training_test_job"
  job_description: "snsdk test training project"
  job_type: "train"
  model: 'meta-llama-3.1-8b-instruct'
  model_version: "1"
  parallel_instances: 1
  load_state: false
  sub_path: ""
  hyperparams:
      batch_size: 8
      max_seq_length: 8192
      run_mode: "balanced"
      vocab_size: 128256
      do_eval: False
      evaluation_strategy: "no"
      fix_rank_rdu_mapping: False
      grad_accumulation_steps: 1
      learning_rate: 0.00001
      logging_steps: 1
      lr_schedule: "fixed_lr"
      save_strategy: "epoch"
      num_train_epochs: 5
      save_interval: 1
      prompt_loss_weight: 0.0
      save_optimizer_state: True
      subsample_eval: 0.01
      subsample_eval_seed: 123
      warmup_steps: 0
      weight_decay: 0.1

model_checkpoint:
  checkpoint_name: "" #set after listing the generated checkpoints after training
  model_name: "llama3.1_8b_fine_tuned"
  model_version: "1"
  model_description: "fine-tuned llama3.8_1b model"
  model_type: "finetuned"

endpoint:
  endpoint_name: "test-endpoint-sql"
  endpoint_description: "endpoint of fine-tuned  llama3.1 8b model"
  endpoint_instances: 1
  hyperparams: null