sambastudio:
  snapi_path: ""
  rdu_arch: "SN40L-8"

dataset:
  dataset_name: "MITRE dataset - Snsdk wrapper"
  dataset_description: "mitre dataset test"
  dataset_path: "/Users/your-user/Documents/ai-starter-kit/utils/fine_tuning/sambastudio_fine_tuning_dataset"
  dataset_apps_availability: 
  - "E5 Mistral Embedding"
  - "Text Embedding" 
  dataset_job_types:
    - "train"
  dataset_source_type: "localMachine"
  dataset_filetype: "hdf5"
  dataset_url: ""
  dataset_language: "english"
  dataset_metadata:
    labels_file: ""
    train_filepath: ""
    validation_filepath: ""
    test_filepath: ""
  
project: 
  project_name: "example project"
  project_description: "this project will be used to test fine-tuning"

job:
  job_name: "training_test_job"
  job_description: "snsdk test training project"
  job_type: "train"
  model: "E5 Large V2"
  model_version: "1"
  parallel_instances: 1
  load_state: false
  sub_path: ""
  hyperparams:
      batch_size: 256
      max_seq_length: 512
      run_mode: "balanced"
      vocab_size: 30522
      learning_rate: 0.00001
      logging_steps: 1
      max_epochs: 1
      save_epoch: 1
      save_steps: -1
      seed: 123
      train_n_passages: 8
      warmup_steps: 0
      weight_decay: 0.1

model_checkpoint:
  checkpoint_name: "" #set after listing the generated checkpoints after training 
  model_name: "snsdk_wrapper_test_e5_large_v2_finetuned_mitre"
  model_description: "wrapper test for e5 finetuned on mitre"
  model_version: "1"
  model_type: "finetuned"

endpoint:
  endpoint_name: "wrapper-test-e5-finetuned-on-mitre"
  endpoint_description: "wrapper test e5 finetuned on mitre"
  endpoint_instances: 1
  hyperparams: null