"""Weights & Biases (W&B) integration for Benchmarking Kit.

This module provides utilities for logging benchmarking results to W&B.
"""

import logging
import os
from typing import Any, Dict, List, Optional

import pandas as pd

logger = logging.getLogger(__name__)

# Lazy import to avoid requiring wandb when not used
_wandb = None


def _get_wandb():
    """Lazy import of wandb to avoid requiring it when not used."""
    global _wandb
    if _wandb is None:
        try:
            import wandb
            _wandb = wandb
        except ImportError:
            raise ImportError(
                'wandb is not installed. Please install it with: pip install wandb'
            )
    return _wandb


class WANDBLogger:
    """Logger for saving benchmarking results to Weights & Biases.

    This class provides methods to:
    - Initialize a W&B run with custom configuration
    - Log summary metrics from benchmark runs
    - Log individual request metrics
    - Log plots/charts to W&B
    - Finish the W&B run
    """

    def __init__(
        self,
        project_name: str = 'sambanova-benchmarking',
        entity: Optional[str] = None,
        run_name: Optional[str] = None,
        config: Optional[Dict[str, Any]] = None,
        tags: Optional[List[str]] = None,
        notes: Optional[str] = None,
        mode: str = 'online',
    ) -> None:
        """Initialize the W&B logger.

        Args:
            project_name: Name of the W&B project. Default: 'sambanova-benchmarking'
            entity: W&B entity (team or username). If None, uses default from wandb login.
            run_name: Optional name for this run. If None, auto-generated by W&B.
            config: Dictionary of configuration parameters to log with the run.
            tags: Optional list of tags for the run.
            notes: Optional notes for the run.
            mode: W&B mode - 'online', 'offline', or 'disabled'. Default: 'online'.
        """
        self.project_name = project_name
        self.entity = entity
        self.run_name = run_name
        self.config = config or {}
        self.tags = tags or []
        self.notes = notes
        self.mode = mode
        self._run = None
        self._initialized = False

    def _get_wandb_run_config(self) -> Dict[str, Any]:
        """Get the W&B run configuration."""
        return {
            'project': self.project_name,
            'entity': self.entity,
            'name': self.run_name,
            'config': self.config,
            'tags': self.tags,
            'notes': self.notes,
            'mode': self.mode,
        }

    def init(self) -> bool:
        """Initialize the W&B run.

        Returns:
            bool: True if initialization was successful, False otherwise.
        """
        try:
            wandb = _get_wandb()

            # Check if wandb is properly initialized
            wandb_config = self._get_wandb_run_config()

            self._run = wandb.init(**{k: v for k, v in wandb_config.items() if v is not None})
            self._initialized = True
            logger.info(f'W&B run initialized: {self._run.url}')
            return True
        except Exception as e:
            logger.warning(f'Failed to initialize W&B run: {e}')
            self._initialized = False
            return False

    def is_initialized(self) -> bool:
        """Check if the W&B run is initialized."""
        return self._initialized and self._run is not None

    def log_metrics(self, metrics: Dict[str, Any], step: Optional[int] = None) -> None:
        """Log metrics to W&B.

        Args:
            metrics: Dictionary of metrics to log.
            step: Optional step number for the metrics.
        """
        if not self.is_initialized():
            logger.warning('W&B run not initialized. Skipping metric logging.')
            return

        try:
            self._run.log(metrics, step=step)
        except Exception as e:
            logger.warning(f'Failed to log metrics to W&B: {e}')

    def log_summary_metrics(
        self,
        summary: Dict[str, Any],
        model_name: str,
        prefix: str = '',
    ) -> None:
        """Log summary metrics from a benchmark run to W&B.

        Args:
            summary: Dictionary containing summary metrics from build_metrics_summary.
            model_name: Name of the model being benchmarked.
            prefix: Optional prefix for metric names (e.g., 'synthetic_', 'custom_').
        """
        if not self.is_initialized():
            logger.warning('W&B run not initialized. Skipping summary metric logging.')
            return

        try:
            wandb_metrics = {}

            # Flatten the summary metrics and log them
            for metric_name, metric_data in summary.items():
                if isinstance(metric_data, dict):
                    # Handle metrics with quantiles, mean, min, max, stddev
                    for stat_name, value in metric_data.items():
                        if stat_name == 'quantiles' and isinstance(value, dict):
                            for quantile, quantile_value in value.items():
                                full_name = f'{prefix}{metric_name}_{quantile}'
                                wandb_metrics[full_name] = quantile_value
                        else:
                            full_name = f'{prefix}{metric_name}_{stat_name}'
                            wandb_metrics[full_name] = value
                else:
                    # Handle simple metrics (strings, numbers)
                    wandb_metrics[f'{prefix}{metric_name}'] = metric_data

            # Add model name as a tag for easy filtering
            wandb_metrics['model_name'] = model_name

            self._run.log(wandb_metrics)
            logger.info(f'Logged summary metrics to W&B for model {model_name}')

        except Exception as e:
            logger.warning(f'Failed to log summary metrics to W&B: {e}')

    def log_individual_responses(
        self,
        responses: List[Dict[str, Any]],
        model_name: str,
    ) -> None:
        """Log individual response metrics as a W&B Table.

        Args:
            responses: List of dictionaries containing per-request metrics.
            model_name: Name of the model being benchmarked.
        """
        if not self.is_initialized():
            logger.warning('W&B run not initialized. Skipping individual response logging.')
            return

        try:
            wandb = _get_wandb()

            # Convert to DataFrame for easier manipulation
            df = pd.DataFrame(responses)

            # Select key columns for the table
            key_columns = [
                'error_code',
                'client_ttft_s',
                'client_end_to_end_latency_s',
                'client_output_token_per_s_per_request',
                'server_ttft_s',
                'server_end_to_end_latency_s',
                'server_output_token_per_s_per_request',
                'number_input_tokens',
                'number_output_tokens',
                'batch_size_used',
            ]

            # Filter to only columns that exist
            available_columns = [col for col in key_columns if col in df.columns]
            table_df = df[available_columns].copy()

            # Create W&B Table
            wandb_table = wandb.Table(dataframe=table_df)

            # Log the table
            self._run.log({f'{model_name}_individual_responses': wandb_table})
            logger.info(f'Logged individual responses table to W&B for model {model_name}')

        except Exception as e:
            logger.warning(f'Failed to log individual responses to W&B: {e}')

    def log_performance_plots(
        self,
        df: pd.DataFrame,
        model_name: str,
    ) -> None:
        """Log performance plots to W&B.

        Args:
            df: DataFrame containing per-request metrics.
            model_name: Name of the model being benchmarked.
        """
        if not self.is_initialized():
            logger.warning('W&B run not initialized. Skipping performance plot logging.')
            return

        try:
            wandb = _get_wandb()

            plots = {}

            # TTFT plot
            if 'client_ttft_s' in df.columns:
                ttft_fig = self._create_distribution_figure(
                    df, 'client_ttft_s', 'Time to First Token (TTFT)', 'TTFT (s)'
                )
                if ttft_fig is not None:
                    plots['ttft_distribution'] = wandb.Image(ttft_fig)

            # End-to-end latency plot
            if 'client_end_to_end_latency_s' in df.columns:
                latency_fig = self._create_distribution_figure(
                    df,
                    'client_end_to_end_latency_s',
                    'End-to-End Latency',
                    'Latency (s)',
                )
                if latency_fig is not None:
                    plots['e2e_latency_distribution'] = wandb.Image(latency_fig)

            # Output throughput plot
            if 'client_output_token_per_s_per_request' in df.columns:
                throughput_fig = self._create_distribution_figure(
                    df,
                    'client_output_token_per_s_per_request',
                    'Output Throughput',
                    'Tokens/sec/request',
                )
                if throughput_fig is not None:
                    plots['output_throughput_distribution'] = wandb.Image(throughput_fig)

            if plots:
                self._run.log(plots)
                logger.info(f'Logged performance plots to W&B for model {model_name}')

        except Exception as e:
            logger.warning(f'Failed to log performance plots to W&B: {e}')

    def _create_distribution_figure(
        self,
        df: pd.DataFrame,
        column: str,
        title: str,
        ylabel: str,
    ) -> Optional[Any]:
        """Create a distribution plot figure.

        Args:
            df: DataFrame containing the data.
            column: Column name to plot.
            title: Plot title.
            ylabel: Y-axis label.

        Returns:
            Figure object or None if creation fails.
        """
        try:
            import matplotlib.pyplot as plt

            valid_df = df[df[column].notna()]
            if valid_df.empty:
                return None

            fig, ax = plt.subplots(figsize=(10, 6))
            valid_df[column].hist(bins=30, ax=ax, edgecolor='black')
            ax.set_xlabel(ylabel)
            ax.set_ylabel('Frequency')
            ax.set_title(f'{model_name}: {title}')
            plt.tight_layout()
            return fig

        except Exception:
            return None

    def log_summary_table(
        self,
        summary_data: List[Dict[str, Any]],
        title: str = 'Benchmark Summary',
    ) -> None:
        """Log a summary table to W&B.

        Args:
            summary_data: List of dictionaries containing summary data.
            title: Title for the table.
        """
        if not self.is_initialized():
            logger.warning('W&B run not initialized. Skipping summary table logging.')
            return

        try:
            wandb = _get_wandb()
            table = wandb.Table(dataframe=pd.DataFrame(summary_data))
            self._run.log({title: table})
        except Exception as e:
            logger.warning(f'Failed to log summary table to W&B: {e}')

    def finish(self) -> None:
        """Finish the W&B run."""
        if self.is_initialized():
            try:
                self._run.finish()
                self._initialized = False
                self._run = None
                logger.info('W&B run finished successfully')
            except Exception as e:
                logger.warning(f'Error finishing W&B run: {e}')


def create_wandb_logger(
    project_name: str = 'sambanova-benchmarking',
    entity: Optional[str] = None,
    run_name: Optional[str] = None,
    config: Optional[Dict[str, Any]] = None,
    tags: Optional[List[str]] = None,
    notes: Optional[str] = None,
    mode: str = 'online',
) -> Optional[WANDBLogger]:
    """Factory function to create a W&B logger.

    Args:
        project_name: Name of the W&B project.
        entity: W&B entity (team or username).
        run_name: Optional name for this run.
        config: Dictionary of configuration parameters.
        tags: Optional list of tags.
        notes: Optional notes.
        mode: W&B mode - 'online', 'offline', or 'disabled'.

    Returns:
        WANDBLogger instance if W&B is available and initialized successfully, None otherwise.
    """
    try:
        logger_instance = WANDBLogger(
            project_name=project_name,
            entity=entity,
            run_name=run_name,
            config=config,
            tags=tags,
            notes=notes,
            mode=mode,
        )
        if logger_instance.init():
            return logger_instance
        return None
    except Exception as e:
        logger.warning(f'Failed to create W&B logger: {e}')
        return None


def is_wandb_available() -> bool:
    """Check if wandb is installed and available.

    Returns:
        bool: True if wandb is available, False otherwise.
    """
    try:
        _get_wandb()
        return True
    except ImportError:
        return False