version: '1'
services:
  web_crawler_retriever_service:
    build: 
      context: ../
      dockerfile: web_crawled_data_retriever/docker/Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/web_crawled_data_retriever/data