version: '1'
services:
  post_call_analysis_service:
    build: 
      context: ../
      args:
        SNAPI: SambaStudio_API_Client-XX.X.X+rcX-py3-none-any.whl
        SNSDK: snsdk-XX.XX.X+rcX-py3-none-any.whl
        SAMBASTUDIO_API: "1234567890abcdef09877654321fedcba1234567890abcdef09877654321fedc"
      dockerfile: post_call_analysis/docker/Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/post_call_analysis/data