sambastudio:
  snapi_path: ""
  rdu_arch: "SN40L-8"

checkpoints:
  - model_name: "Suzume-Llama-3-8B-Multilingual"
    checkpoint_path: '/Users/my_user/Documents/ai-starter-kit/e2e_fine_tuning/data/models/models--lightblue--suzume-llama-3-8B-multilingual/snapshots/0cb15aa9ec685eef494f9a15f65aefcfe3c04c66'
    publisher: "lightblue"
    description: "Suzume 8B, a multilingual finetune of Llama "
    param_count: 8
    model_arch: "llama" 
    seq_length: 8192 
    vocab_size: 128256 
    app_id: "61fa0993-04a2-42ca-9db1-1eff693ea978"
