sambastudio:
  snapi_path: ""
  rdu_arch: "SN40L-8"

project:
  project_name: "byoc fine-tuning project"
  project_description: "this project will be used to test the BYOC and Fine-tuning e2e pipeline implementation"

job:
  job_name: "e2e_fc_taining_job"
  job_description: "e2e finetuning training job public health for suzume multilingual"
  job_type: "train"
  model: "Suzume-Llama-3-8B-Multilingual"
  model_version: "1"
  dataset_name: "publichealth"
  parallel_instances: 1
  load_state: false
  sub_path: ""
  hyperparams:
    batch_size: 8
    do_eval: false
    eval_steps: 5
    evaluation_strategy: "no"
    learning_rate: 0.00001
    logging_steps: 1
    lr_schedule: "fixed_lr"
    max_sequence_length: 8192
    num_iterations: 10
    prompt_loss_weight: 0.0
    save_optimizer_state: True
    save_steps: 5
    skip_checkpoint: False
    subsample_eval: 0.01
    subsample_eval_seed: 123
    use_token_type_ids: true
    vocab_size: 128256
    warmup_steps: 0
    weight_decay: 0.1

model_checkpoint: 
  checkpoint_name: "" #set after listing the generated checkpoints after training
  model_name: "Suzume-Llama-3-8B-Multilingual-Publichealth"
  model_description: "finetuned suzume multilingual in public health qa dataset"
  model_type: "finetuned"