sambastudio:
  snapi_path: ""
  rdu_arch: "SN40L-8"

project:
  project_name: "byoc-fine-tuning-project"
  project_description: "this project will be used to test the BYOC and Fine-tuning e2e pipeline implementation"

job:
  job_name: "e2e_fc_taining_job"
  job_description: "e2e finetuning training job public health for suzume multilingual"
  job_type: "train"
  model: "Suzume-Llama-3-8B-Multilingual"
  model_version: "1"
  dataset_name: "publichealth"
  parallel_instances: 1
  load_state: false
  sub_path: ""
  hyperparams:
      batch_size: 8
      max_seq_length: 8192
      run_mode: "balanced"
      vocab_size: 128256
      do_eval: False
      evaluation_strategy: "no"
      fix_rank_rdu_mapping: False
      grad_accumulation_steps: 1
      learning_rate: 0.00001
      logging_steps: 1
      lr_schedule: "fixed_lr"
      save_strategy: "epoch"
      num_train_epochs: 5
      save_interval: 1
      prompt_loss_weight: 0.0
      save_optimizer_state: True
      subsample_eval: 0.01
      subsample_eval_seed: 123
      warmup_steps: 0
      weight_decay: 0.1

model_checkpoint: 
  checkpoint_name: "" #set after listing the generated checkpoints after training
  model_name: "Suzume-Llama-3-8B-Multilingual-Publichealth"
  model_version: "1"
  model_description: "finetuned suzume multilingual in public health qa dataset"
  model_type: "finetuned"