sambastudio:
  snapi_path: ""
  rdu_arch: "SN40L-8"

job:
  job_type: "deploy"

spec_decoding:
  model_name: "Meta-Llama-3.3-70B-Instruct-SD"
  target_model: "Meta-Llama-3.3-70B-Instruct"
  target_model_version: "1"
  draft_model: "Meta-Llama-3-8B-Instruct"
  draft_model_version: "1"
